### PR TITLE
redirect free gmail post to new custom email guide

### PR DESCRIPTION
**Pull request by chriswrites**

### CODE REVIEW

**Comment by holic** [comment]
Needs a `.redirect` extension.

**Comment by chriswrites** [comment]
Still doesn't work. Guess I can't redirect to a specific section of a post?

**Comment by holic** [comment]
This also needs to remove the link from the sidebar - the old post shows up blank in the sidebar on the homepage (first link).

**Comment by holic** [comment]
List of popular posts is here: https://github.com/iwantmyname/blog/blob/master/templates/sidebar.tmpl

**Comment by chriswrites** [comment]
Hope that works?

**Pull request merged**
