### PR TITLE
Add draft of new team assembles post

### PR DESCRIPTION
**Pull request by chriswrites**
Looking for more to add to this post. Help!

### CODE REVIEW

**Comment by holic** [comment]
To give this post a bit more contex, it might be worth noting and/or linking to the articles mentioning our experimental company structure and culture (plus the interlinking gains!):
https://iwantmyname.com/blog/2014/05/culture-at-iwmn-part-one.html

**Comment by treitnauer** [comment]
It would be nice to use our new team photo for the post.

**Comment by holic** [comment]
@chriswrites Any update on this?

**Comment by treitnauer** [comment]
Checked with Chris a few weeks ago and his reply was:

> Just not sure what it should say. I just want it to mean something, you know?

It's a bit too late to post it anyway so perhaps we should just not publish anything.

**Pull request closed without merging**
